# Some common recipes

# Download a target
get-target target="all":
    ./fuzz-workflow.py -t "{{target}}" --skip-run --skip-report --parallel

# Execute an exploratory workflow with a few targets and random seed
fuzz-local target="all":
    ./fuzz-workflow.py -t "{{target}}" --skip-get --report-publish --parallel --source local --rand-seed --max-mutations 5

# Execute a trace workflow with a few targets and publish the corresponding reports
fuzz-trace target="all":
    ./fuzz-workflow.py -t "{{target}}" --skip-get --report-publish --parallel --source trace
